name: Test Runner Connection

on:
  push:
    branches:
      - master  # بدّلناها لـ master

jobs:
  test-runner:
    runs-on: self-hosted  # هادي المهمة غادي تتنفذ فـ الجهاز ديالك
    steps:
      - name: Say Hello from Self-Hosted Runner
        run: echo "✅ Ana khdam mn dak self-hosted runner!"
